import Head from "next/head";
import styles from "styles/Home.module.css";
import { Montserrat, Karla } from "@next/font/google";
import "@fortawesome/fontawesome-svg-core/styles.css";
import {
	faBolt,
	faFilter,
	faTimes,
	faAngleLeft,
	faAngleRight,
	faBars,
	faAngleDown
} from "@fortawesome/free-solid-svg-icons";
import { ComicGrid, Header, HeroImage, IntroPanel, Footer } from "components";
import AppContextProvider from "state/AppContext";
// Using this syntax, because error is caused using other syntax for whatever reason
const { library, config } = require("@fortawesome/fontawesome-svg-core");

const karla = Karla({ variable: "--karla", subsets: ["latin"] });
const montserrat = Montserrat({ variable: "--montserrat", subsets: ["latin"] });

config.autoAddCss = false;
library.add(faBolt, faFilter, faTimes, faAngleLeft, faAngleRight, faBars, faAngleDown);

export default function Home() {
	return (
		<div
			className={`${styles.container} ${karla.variable} ${montserrat.variable}`}
		>
			<Head>
				<title>CMS React Training</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<AppContextProvider>
				<Header />
				<HeroImage />
				<main className={styles.main}>
					<IntroPanel />
					<ComicGrid />
				</main>
				<Footer />
			</AppContextProvider>
		</div>
	);
}
